version: "3"
services:
  starship-cost-api:
    image: starship-cost-api
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:80"
    environment:
      - SWAPI_URL=https://swapi.dev/api/
      - REDIS=redis://redis
    volumes:
      - ./backend:/code
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  starship-charts:
    image: starship-charts
    build:
      context: ./starship-charts
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./starship-charts:/starship-charts