FROM node:18-alpine

WORKDIR /starship-charts/

COPY public/ /starship-charts/public
COPY src/ /starship-charts/src
COPY package.json /starship-charts/

RUN npm install

CMD ["npm", "start"]